name: Build and publish package
on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: Ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
    env:
      PACKAGE_NAME: "lib-gh"
    steps:
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 1
          ref: main

      - name: Install dependencies
        run: "npm install"

      - name: Build
        run: "npm run build"

      - name: Release
        if: success()
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
        run: npx semantic-release
