name: Build and publish package
on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: Ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
    env:
      PACKAGE_NAME: "lib-gh"
    steps:
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 1
          ref: main

      - name: Install dependencies
        run: "npm install"

      - name: Build
        run: "npm run build"

      - name: Release
        if: success()
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  create_pr_to_deriv_app:
    runs-on: Ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    needs: [build_and_publish]
    env:
      PACKAGE_NAME: "lib-gh"
    steps:
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: 18.x

      - name: Checkout deriv-app
        uses: "binary-com/SmartCharts/.github/actions/checkout@master"
        with:
          repository: "farhan-nurzi-deriv/deriv-app"
          path: deriv-app
          ref: master

      - name: Check new version
        id: check_new_version
        run: |
          new_version=$(npm show $PACKAGE_NAME version)
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Insall jq
        run: sudo apt-get install jq

      - name: Update core package.json
        run: |
          cd deriv-app/packages/core
          tmp=$(mktemp)
          jq --indent 4 ".dependencies[\"@deriv/deriv-charts\"] = \"^1.0.0\"" package.json > "$tmp" && mv "$tmp" package.json

      - name: Update trader package.json
        run: |
          cd deriv-app/packages/trader
          tmp=$(mktemp)
          jq --indent 4 ".dependencies[\"@deriv/deriv-charts\"] = \"^1.0.0\"" package.json > "$tmp" && mv "$tmp" package.json

      - name: Update bot-web-ui package.json
        run: |
          cd deriv-app/packages/bot-web-ui
          tmp=$(mktemp)
          jq --indent 4 ".dependencies[\"@deriv/deriv-charts\"] = \"^1.0.0\"" package.json > "$tmp" && mv "$tmp" package.json

      - name: Update root package-lock.json
        run: |
          cd deriv-app
          npm i -g lerna@^5.5.1
          npm ci && lerna link && lerna bootstrap --hoist --strict && lerna link

      - name: Create Pull Request to deriv-app repo
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "chore: update ${{ env.PACKAGE_NAME }} to ${{ steps.check_new_version.outputs.new_version }}"
          title: "chore: update ${{ env.PACKAGE_NAME }} to ${{ steps.check_new_version.outputs.new_version }}"
          body: "This PR updates ${{ env.PACKAGE_NAME }} to ${{ steps.check_new_version.outputs.new_version }}"
          branch: "chore/update-${{ env.PACKAGE_NAME }}-to-${{ steps.check_new_version.outputs.new_version }}"
          base: "master"
          path: "deriv-app"
